export const UPPER_GARMENT_PROMPT_VERSION = 'upper-garment-v2';

export function buildUpperGarmentPrompt() {
  return [
    `Versão do prompt: ${UPPER_GARMENT_PROMPT_VERSION}`,
    '',
    'OBJETIVO ÚNICO',
    'Edite exclusivamente a roupa da parte superior do corpo da pessoa da Imagem 1, usando a roupa da Imagem 2 como referência visual.',
    '',
    'PAPEL DAS IMAGENS',
    '- Imagem 1: fonte imutável da pessoa, identidade, pose, câmera, cenário e iluminação originais.',
    '- Imagem 2: única referência visual da roupa que deve substituir a roupa superior existente na Imagem 1.',
    '',
    'ELEMENTOS IMUTÁVEIS DA IMAGEM 1',
    'Preserve identidade, rosto, formato da cabeça, cabelo, textura natural da pele, expressão, mãos, dedos, pose, posição corporal, anatomia, parte inferior do corpo, acessórios, relógios e pulseiras.',
    'Preserve também fundo, objetos do cenário, perspectiva, lente aparente, distância da câmera, profundidade de campo, exposição, balanço de branco, contraste e enquadramento original.',
    '',
    'REGIÃO EDITÁVEL',
    'Altere somente a roupa superior, seu contorno estritamente necessário, oclusões naturais, sombras de contato, dobras e a interação da peça com braços, pescoço, cabelo e tronco.',
    'Uma peça volumosa pode alterar o contorno visual da roupa, mas nunca a geometria real da pose, a anatomia ou a identidade da pessoa.',
    '',
    'FIDELIDADE DA ROUPA DA IMAGEM 2',
    'Reproduza com máxima fidelidade somente o que estiver visível: cor, formato, gola, abertura, punhos, barra, largura, comprimento, mangas, caimento, volume, espessura, rigidez, elasticidade, brilho e material.',
    'Preserve trama, textura, acolchoamento, nervuras, costuras, espaçamento e direção das costuras, zíperes, botões, bolsos, estampas, padrões, logo, posição, escala e orientação.',
    '',
    'MARCAS, LOGOS E TEXTOS',
    'Não espelhe logos ou textos, não redesenhe letras, não corrija nem complete palavras e não altere posição ou escala da marca.',
    'Se um texto ou símbolo estiver ilegível, não invente: preserve apenas os elementos realmente visíveis na referência.',
    '',
    'OCLUSÕES E INTEGRAÇÃO FÍSICA',
    'Mantenha correta a ordem das camadas: cabelo, gola, braços, mãos, acessórios e roupa devem permanecer à frente ou atrás conforme a pose original.',
    'Crie sombras coerentes sob o queixo, na gola, nos braços, nas dobras e nos pontos de contato com o corpo.',
    'Preserve a cor intrínseca da peça, aplicando somente a iluminação compatível com a cena da Imagem 1.',
    '',
    'REGRA DE INCERTEZA',
    'Faça inferência conservadora apenas nas laterais, costas, áreas ocultas pelos braços, parte interna da gola e dobras necessárias para vestir a peça na pose.',
    'Não invente marcas, textos, símbolos, estampas, bolsos, zíperes, costuras ou detalhes de design visíveis que não existam na Imagem 2.',
    '',
    'PROIBIÇÕES FINAIS',
    'Não mude identidade, rosto, penteado, expressão, pose ou enquadramento. Não aplique embelezamento, correção de pele, retoque global, zoom, crop ou recomposição.',
    'Não limpe nem substitua o fundo, não mude globalmente a iluminação, não remova acessórios e não crie membros, dedos ou costuras duplicados.',
    'O resultado deve parecer uma fotografia original e fisicamente coerente, sem aparência de montagem artificial.',
  ].join('\n');
}
