import { useMemo, useRef, useState } from 'react';
import { AlertCircle, FolderPlus, Pause, Play, RotateCcw, Square, Upload } from 'lucide-react';

const money = (value) => Number.isFinite(value) ? new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(value) : 'Não informado';
const terminal = new Set(['completed', 'failed', 'cancelled', 'interrupted']);
export default function BatchesPage({ batchesState, templates, keyConfigured, onOpenResult }) {
  const { batches, selected, select, status, error, submit, action } = batchesState; const [name, setName] = useState(''); const [templateId, setTemplateId] = useState(''); const [files, setFiles] = useState([]); const [confirmed, setConfirmed] = useState(false); const [submitting, setSubmitting] = useState(false); const [formError, setFormError] = useState(''); const input = useRef();
  const activeTemplates = templates.filter((template) => template.valid && template.active !== false);
  const estimated = files.length * 0.034;
  const selectedTemplate = useMemo(() => activeTemplates.find((template) => template.id === templateId), [activeTemplates, templateId]);
  async function create(event) { event.preventDefault(); setFormError(''); if (!name.trim() || !templateId || !files.length || !confirmed) { setFormError('Preencha o nome, selecione um template, adicione roupas e confirme os créditos.'); return; } setSubmitting(true); try { await submit({ name, templateId, files }); setName(''); setFiles([]); setConfirmed(false); } catch (e) { setFormError(e.message); } finally { setSubmitting(false); } }
  function accept(next) { setFiles((current) => [...current, ...Array.from(next)].slice(0, 200)); }
  return <div className="space-y-7"><header className="border-b border-slate-200 pb-6"><p className="text-xs font-semibold uppercase tracking-[.18em] text-slate-500">PRIME IA STUDIO</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Produção em Lotes</h1><p className="mt-2 text-sm text-slate-500">Uma roupa por vez, com custo e progresso persistidos localmente.</p></header>
    <section className="grid gap-6 xl:grid-cols-[minmax(360px,.85fr)_minmax(0,1.15fr)]"><form onSubmit={create} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-5 flex items-center gap-2 font-semibold"><FolderPlus size={18}/> Novo lote</div><label className="block text-sm font-medium">Nome<input value={name} onChange={(e)=>setName(e.target.value)} className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2" maxLength="100" /></label><label className="mt-4 block text-sm font-medium">Template<select value={templateId} onChange={(e)=>setTemplateId(e.target.value)} className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2"><option value="">Selecione um template</option>{activeTemplates.map((template)=><option key={template.id} value={template.id}>{template.label}</option>)}</select></label>{selectedTemplate && <p className="mt-2 text-xs text-slate-500">{selectedTemplate.width}×{selectedTemplate.height} · {selectedTemplate.mimeType}</p>}
      <div onDragOver={(e)=>e.preventDefault()} onDrop={(e)=>{e.preventDefault();accept(e.dataTransfer.files)}} className="mt-4 rounded-xl border border-dashed border-slate-300 bg-slate-50 p-4 text-center"><Upload className="mx-auto text-slate-500" size={20}/><p className="mt-2 text-sm">Arraste roupas ou selecione arquivos</p><button type="button" onClick={()=>input.current?.click()} className="mt-2 text-sm font-medium text-slate-700 underline">Selecionar imagens</button><input ref={input} className="hidden" type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={(e)=>accept(e.target.files)} /></div>
      <ul className="mt-3 max-h-32 space-y-1 overflow-auto text-xs text-slate-600">{files.map((file,index)=><li key={`${file.name}-${index}`} className="flex justify-between gap-2"><span className="truncate">{file.name} · {(file.size/1024/1024).toFixed(2)} MB</span><button type="button" className="text-rose-600" onClick={()=>setFiles((current)=>current.filter((_,i)=>i!==index))}>Remover</button></li>)}</ul><div className="mt-4 rounded-lg bg-slate-50 p-3 text-sm"><p>{files.length} itens · estimativa por item US$ 0.034</p><p className="mt-1 font-semibold">Total estimado: {money(estimated)}</p><p className="mt-1 text-xs text-slate-500">O custo real pode variar e só é registrado quando informado pelo provedor.</p></div><label className="mt-4 flex gap-2 text-xs text-slate-600"><input type="checkbox" checked={confirmed} onChange={(e)=>setConfirmed(e.target.checked)}/> Confirmo que o lote poderá consumir créditos.</label>{(formError || error) && <p className="mt-3 flex gap-2 text-sm text-rose-700"><AlertCircle size={16}/>{formError || error}</p>}<button disabled={submitting || !keyConfigured} className="mt-4 w-full rounded-lg bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-40">{submitting ? 'Criando…' : keyConfigured ? 'Criar lote para revisão' : 'Configure a chave para continuar'}</button></form>
      <div className="space-y-3"><div className="flex items-center justify-between"><h2 className="font-semibold">Lotes locais</h2><span className="text-xs text-slate-500">{status === 'loading' ? 'Atualizando…' : `${batches.length} lote(s)`}</span></div>{!batches.length ? <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center text-sm text-slate-500">Nenhum lote criado ainda.</div> : batches.map((batch)=><button type="button" key={batch.id} onClick={()=>select(batch)} className={`w-full rounded-xl border bg-white p-4 text-left shadow-sm ${selected?.id===batch.id?'border-slate-900':'border-slate-200'}`}><div className="flex justify-between gap-3"><strong>{batch.name}</strong><span className="rounded-full bg-slate-100 px-2 py-0.5 text-xs">{batch.status}</span></div><p className="mt-1 text-xs text-slate-500">{batch.templateLabel} · {batch.totalItems} itens · {money(batch.actualCostUsd)}</p></button>)}</div></section>
    {selected && <BatchDetail batch={selected} action={action} onOpenResult={onOpenResult}/>}</div>;
}
function BatchDetail({ batch, action, onOpenResult }) { const finished=batch.items.filter((item)=>terminal.has(item.status)).length; const canStart=['ready','paused','interrupted'].includes(batch.status)&&batch.items.some((item)=>item.status==='queued'); return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-semibold">{batch.name}</h2><p className="text-sm text-slate-500">{batch.templateLabel} · {batch.status}</p></div><div className="flex gap-2">{canStart&&<button onClick={()=>action(batch.status==='paused'?'resume':'start',{confirmPaid:true})} className="rounded-lg bg-slate-950 px-3 py-2 text-sm text-white"><Play className="mr-1 inline" size={15}/>{batch.status==='paused'?'Retomar':'Iniciar'}</button>}{batch.status==='running'&&<button onClick={()=>action('pause')} className="rounded-lg border px-3 py-2 text-sm"><Pause className="mr-1 inline" size={15}/>Pausar</button>}{['ready','running','paused','interrupted'].includes(batch.status)&&<button onClick={()=>action('cancel')} className="rounded-lg border border-rose-200 px-3 py-2 text-sm text-rose-700"><Square className="mr-1 inline" size={15}/>Cancelar</button>}</div></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full bg-slate-900" style={{width:`${batch.totalItems ? finished/batch.totalItems*100 : 0}%`}}/></div><p className="mt-2 text-xs text-slate-500">{finished}/{batch.totalItems} finalizados · Estimado {money(batch.estimatedCostUsd)} · Real {money(batch.actualCostUsd)}</p><ul className="mt-5 divide-y divide-slate-100">{batch.items.map((item)=><li key={item.id} className="flex flex-wrap items-center justify-between gap-2 py-3 text-sm"><div><p className="font-medium">{item.originalFileName}</p><p className="text-xs text-slate-500">{item.garmentDimensions?.width}×{item.garmentDimensions?.height} · {item.garmentMime} · {item.status}{item.durationMs ? ` · ${(item.durationMs/1000).toFixed(1)}s`:''}</p>{item.safeError&&<p className="text-xs text-rose-700">{item.safeError.message}</p>}</div>{item.resultId&&<button onClick={()=>onOpenResult?.(item.resultId)} className="text-sm font-medium underline">Abrir resultado</button>}</li>)}</ul></section>; }
