import { AlertCircle, CalendarDays, Check, Clock3, Download, ExternalLink, Flag, ImagePlus, Loader2, LockKeyhole, Megaphone, Pencil, Plus, RefreshCw, Sparkles, Trash2, X } from 'lucide-react';
import { useMemo, useState } from 'react';
import { marketingAssetUrl } from '../api/marketingClient.js';

const TABS = [['planning', 'Planejamento'], ['calendar', 'Calendário'], ['stories', 'Stories'], ['history', 'Histórico']];

export default function MarketingPage({ marketing, onOpenResult = () => {} }) {
  const [tab, setTab] = useState('planning');
  const [editing, setEditing] = useState(null);
  const [confirmDelete, setConfirmDelete] = useState(null);
  const [newWeekStart, setNewWeekStart] = useState(currentMonday());
  const nextStory = useMemo(() => findNext(marketing.selected?.stories || []), [marketing.selected]);
  const readOnly = marketing.selected?.status === 'closed';

  if (marketing.status === 'loading' || marketing.status === 'idle') return <Loading />;
  if (marketing.status === 'error') return <ErrorState message={marketing.error} onRetry={marketing.load} />;

  return <>
    <header className="mb-7 border-b border-slate-200/80 pb-6">
      <div className="mb-3 flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.18em] text-slate-500"><Megaphone size={14} /> PRIME IA STUDIO</div>
      <div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><h1 className="text-3xl font-semibold tracking-[-0.035em] text-slate-950">Marketing Studio</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Planeje a semana e transforme resultados aprovados em Stories 9:16 prontos para publicação.</p></div><div className="flex flex-col gap-2 sm:flex-row sm:items-end"><label><span className="mb-1 block text-[11px] font-semibold uppercase tracking-wide text-slate-400">Segunda-feira</span><input type="date" aria-label="Início da nova semana" value={newWeekStart} onChange={(event) => setNewWeekStart(mondayForDate(event.target.value))} className="rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm"/></label><button type="button" disabled={marketing.busy} onClick={() => marketing.createWeek(newWeekStart).catch(() => {})} className="inline-flex items-center justify-center gap-2 rounded-xl bg-slate-950 px-4 py-3 text-sm font-semibold text-white disabled:opacity-50"><Plus size={16}/> Nova semana</button></div></div>
    </header>

    {marketing.error && <div role="alert" className="mb-5 flex items-center gap-2 rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-800"><AlertCircle size={16}/>{marketing.error}</div>}

    <div className="mb-6 flex gap-2 overflow-x-auto pb-1" aria-label="Áreas do Marketing Studio">{TABS.map(([value, label]) => <button key={value} type="button" onClick={() => setTab(value)} aria-pressed={tab === value} className={`whitespace-nowrap rounded-full border px-4 py-2 text-xs font-semibold ${tab === value ? 'border-slate-950 bg-slate-950 text-white' : 'border-slate-200 bg-white text-slate-600'}`}>{label}</button>)}</div>

    {marketing.weeks.length === 0 ? <EmptyWeek onCreate={() => marketing.createWeek(newWeekStart).catch(() => {})} /> : <div className="grid gap-6 xl:grid-cols-[260px_minmax(0,1fr)]">
      <aside className="rounded-2xl border border-slate-200 bg-white p-3 shadow-sm"><p className="px-2 pb-3 pt-1 text-xs font-semibold uppercase tracking-wider text-slate-400">Semanas locais</p><div className="space-y-1">{marketing.weeks.map((week) => <button key={week.id} type="button" onClick={() => marketing.select(week.id).catch(() => {})} className={`w-full rounded-xl px-3 py-3 text-left ${week.id === marketing.selected?.id ? 'bg-slate-950 text-white' : 'text-slate-700 hover:bg-slate-50'}`}><span className="block text-sm font-semibold">{formatWeek(week.weekStart)}</span><span className={`mt-1 block text-xs ${week.id === marketing.selected?.id ? 'text-slate-300' : 'text-slate-400'}`}>{week.stories.length} Stories · {weekLabel(week.status)}</span></button>)}</div></aside>
      <main className="min-w-0 space-y-5">
        <WeekHeader week={marketing.selected} busy={marketing.busy} onApprove={marketing.approveWeek} onDraft={marketing.draftWeek} onClose={marketing.closeWeek} onDelete={() => setConfirmDelete('week')} />
        {readOnly && <div role="status" className="flex items-center gap-2 rounded-2xl border border-slate-200 bg-slate-100 p-4 text-sm font-medium text-slate-700"><LockKeyhole size={17}/> Semana encerrada: consulta e downloads permanecem disponíveis, mas o planejamento não pode mais ser alterado.</div>}
        {nextStory && <div className="flex items-center gap-3 rounded-2xl border border-indigo-100 bg-indigo-50 p-4"><div className="rounded-xl bg-white p-2 text-indigo-600"><Clock3 size={18}/></div><div><p className="text-xs font-semibold uppercase tracking-wide text-indigo-500">Próxima publicação</p><p className="mt-1 text-sm font-semibold text-slate-900">{nextStory.productLabel} · {formatDate(nextStory.scheduledDate)} às {nextStory.scheduledTime}</p><p className="mt-0.5 text-xs text-slate-500">{nextStory.categoryLabel || 'Sem categoria'} · {editorialLabel(nextStory.editorialStatus)}</p></div></div>}
        {tab === 'planning' && <Planning week={marketing.selected} sources={marketing.sources} layouts={marketing.layouts} busy={marketing.busy} readOnly={readOnly} editing={editing} onPropose={(items) => marketing.proposeWeek(items).catch(() => {})} onEdit={setEditing} onSave={(story) => { const action = editing ? marketing.updateStory(editing.id, story) : marketing.addStory(story); action.then(() => setEditing(null)).catch(() => {}); }} onCancel={() => setEditing(null)} onDelete={(id) => setConfirmDelete(id)} />}
        {tab === 'calendar' && <CalendarView week={marketing.selected} readOnly={readOnly} onEdit={(story) => { setEditing(story); setTab('planning'); }} />}
        {tab === 'stories' && <StoriesView week={marketing.selected} layouts={marketing.layouts} busy={marketing.busy} readOnly={readOnly} onRender={(id) => marketing.renderStory(id).catch(() => {})} onStatus={(id, value) => marketing.setEditorialStatus(id, value).catch(() => {})} onOpenResult={onOpenResult} onEdit={(story) => { setEditing(story); setTab('planning'); }} />}
        {tab === 'history' && <HistoryView weeks={marketing.weeks} onSelect={(id) => marketing.select(id).then(() => setTab('calendar')).catch(() => {})} />}
      </main>
    </div>}

    {confirmDelete && (confirmDelete === 'week' || !readOnly) && <ConfirmDialog title={confirmDelete === 'week' ? 'Excluir esta semana?' : 'Excluir este Story?'} body="Os arquivos locais relacionados também serão removidos. Esta ação não pode ser desfeita." busy={marketing.busy} onCancel={() => setConfirmDelete(null)} onConfirm={() => { const action = confirmDelete === 'week' ? marketing.removeWeek() : marketing.removeStory(confirmDelete); action.then(() => setConfirmDelete(null)).catch(() => {}); }} />}
  </>;
}

function Planning({ week, sources, layouts, busy, readOnly, editing, onPropose, onEdit, onSave, onCancel, onDelete }) {
  if (readOnly) return <div className="space-y-3">{week.stories.map((story) => <StoryRow key={story.id} story={story} readOnly />)}</div>;
  return <div className="space-y-5">{week.stories.length === 0 && <ProposalBuilder sources={sources} busy={busy} onPropose={onPropose}/>}<div className="grid gap-5 2xl:grid-cols-[minmax(340px,0.8fr)_minmax(0,1.2fr)]"><StoryForm key={editing?.id || `new-${week.id}-${week.stories.length}`} week={week} sources={sources} layouts={layouts} story={editing} busy={busy} onSave={onSave} onCancel={onCancel}/><div className="space-y-3">{week.stories.length === 0 ? <EmptyStories /> : week.stories.map((story) => <StoryRow key={story.id} story={story} onEdit={() => onEdit(story)} onDelete={() => onDelete(story.id)} />)}</div></div></div>;
}

function ProposalBuilder({ sources, busy, onPropose }) { const [items, setItems] = useState({}); const selected = sources.filter((source) => items[source.id]?.selected).map((source) => ({ sourceResultId: source.id, productLabel: items[source.id].productLabel || source.productHint || source.templateLabel, priority: Boolean(items[source.id].priority) })); const update = (id, changes) => setItems((current) => ({ ...current, [id]: { productLabel: sources.find((source) => source.id === id)?.productHint || '', ...current[id], ...changes } })); return <section className="rounded-2xl border border-indigo-100 bg-indigo-50/60 p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-sm font-semibold text-slate-950">Proposta semanal automática</h2><p className="mt-1 text-xs leading-5 text-slate-500">Selecione os produtos. Prioridades entram primeiro e as categorias são alternadas de forma determinística.</p></div><button type="button" disabled={busy || !selected.length} onClick={() => onPropose(selected)} className="inline-flex items-center justify-center gap-2 rounded-xl bg-indigo-600 px-4 py-2.5 text-xs font-semibold text-white disabled:opacity-40"><Sparkles size={15}/> Montar proposta ({selected.length})</button></div><div className="mt-4 grid gap-2 lg:grid-cols-2">{sources.map((source) => <div key={source.id} className="rounded-xl border border-white bg-white p-3"><label className="flex items-start gap-3"><input type="checkbox" checked={Boolean(items[source.id]?.selected)} onChange={(event) => update(source.id, { selected: event.target.checked })} className="mt-1"/><span className="min-w-0 flex-1"><span className="block truncate text-xs font-semibold text-slate-900">{source.templateLabel || source.id}</span><span className="mt-0.5 block text-[11px] text-slate-500">{source.categoryLabel || 'Sem categoria'}</span></span><span className="inline-flex items-center gap-1 text-[11px] font-medium text-amber-700"><input type="checkbox" aria-label={`Priorizar ${source.templateLabel || source.id}`} checked={Boolean(items[source.id]?.priority)} disabled={!items[source.id]?.selected} onChange={(event) => update(source.id, { priority: event.target.checked })}/><Flag size={12}/> Prioridade</span></label>{items[source.id]?.selected && <input aria-label={`Produto de ${source.templateLabel || source.id}`} value={items[source.id]?.productLabel || ''} onChange={(event) => update(source.id, { productLabel: event.target.value })} maxLength={80} className={`${inputClass} mt-2`} />}</div>)}</div></section>; }

function StoryForm({ week, sources, layouts, story, busy, onSave, onCancel }) {
  const initial = story
    ? { ...story, priceText: story.priceText || '', headline: story.headline || '', ctaText: story.ctaText || '' }
    : { sourceResultId: sources[0]?.id || '', sourceAssetVariant: 'original', productLabel: '', priority: false, priceText: '', headline: '', ctaText: 'Saiba mais', storyTemplateId: layouts[0]?.id || 'product-highlight', scheduledDate: week.weekStart, scheduledTime: '10:00', order: week.stories.length + 1 };
  const [form, setForm] = useState(initial);
  const selectedSource = sources.find((source) => source.id === form.sourceResultId);
  const set = (field) => (event) => setForm((current) => ({ ...current, [field]: field === 'order' ? Number(event.target.value) : event.target.value }));
  const valid = form.sourceResultId && form.productLabel.trim() && form.scheduledDate && form.scheduledTime && form.order > 0;
  return <form onSubmit={(event) => { event.preventDefault(); if (valid) onSave(form); }} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="text-base font-semibold text-slate-950">{story ? 'Editar Story' : 'Adicionar Story'}</h2><p className="mt-1 text-xs text-slate-500">Somente resultados aprovados estão disponíveis.</p></div>{story && <button type="button" onClick={onCancel} className="rounded-lg p-2 text-slate-400 hover:bg-slate-100"><X size={17}/></button>}</div>
    <div className="mt-5 space-y-4"><Field label="Resultado aprovado"><select value={form.sourceResultId} onChange={set('sourceResultId')} disabled={busy} className={inputClass}><option value="">Selecione</option>{sources.map((source) => <option key={source.id} value={source.id}>{source.templateLabel || source.id}</option>)}</select></Field>
    <Field label="Variante"><select value={form.sourceAssetVariant} onChange={set('sourceAssetVariant')} disabled={busy} className={inputClass}><option value="original">Original</option>{selectedSource?.brandedAvailable && <option value="branded">Com Branding</option>}</select></Field>
    <Field label="Nome ou código do produto"><input value={form.productLabel} maxLength={80} onChange={set('productLabel')} disabled={busy} className={inputClass}/></Field>
    <label className="flex items-center gap-2 rounded-xl border border-amber-100 bg-amber-50 px-3 py-2.5 text-xs font-semibold text-amber-800"><input type="checkbox" checked={Boolean(form.priority)} onChange={(event) => setForm((current) => ({ ...current, priority: event.target.checked }))} disabled={busy}/><Flag size={14}/> Produto prioritário</label>
    <div className="grid gap-3 sm:grid-cols-2"><Field label="Preço (opcional)"><input value={form.priceText} maxLength={40} onChange={set('priceText')} disabled={busy} placeholder="R$ 99,90" className={inputClass}/></Field><Field label="Layout"><select value={form.storyTemplateId} onChange={set('storyTemplateId')} disabled={busy} className={inputClass}>{layouts.map((layout) => <option key={layout.id} value={layout.id}>{layout.label}</option>)}</select></Field></div>
    <Field label="Chamada curta (opcional)"><input value={form.headline} maxLength={90} onChange={set('headline')} disabled={busy} placeholder="Condição no PIX ou cartão" className={inputClass}/></Field><Field label="CTA (opcional)"><input value={form.ctaText} maxLength={40} onChange={set('ctaText')} disabled={busy} className={inputClass}/></Field>
    <div className="grid grid-cols-3 gap-3"><Field label="Dia"><input type="date" min={week.weekStart} max={addDays(week.weekStart, 6)} value={form.scheduledDate} onChange={set('scheduledDate')} disabled={busy} className={inputClass}/></Field><Field label="Horário"><input type="time" value={form.scheduledTime} onChange={set('scheduledTime')} disabled={busy} className={inputClass}/></Field><Field label="Ordem"><input type="number" min="1" max="999" value={form.order} onChange={set('order')} disabled={busy} className={inputClass}/></Field></div></div>
    {sources.length === 0 && <p className="mt-4 rounded-xl bg-amber-50 p-3 text-xs text-amber-800">Aprove um resultado na tela Resultados para começar.</p>}<button type="submit" disabled={busy || !valid} className="mt-5 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-slate-950 px-4 py-3 text-sm font-semibold text-white disabled:opacity-40">{busy ? <Loader2 size={16} className="animate-spin"/> : story ? <Check size={16}/> : <Plus size={16}/>} {story ? 'Salvar alterações' : 'Adicionar à semana'}</button></form>;
}

function WeekHeader({ week, busy, onApprove, onDraft, onClose, onDelete }) { const closed = week.status === 'closed'; return <div className="flex flex-col gap-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm md:flex-row md:items-center md:justify-between"><div><div className="flex items-center gap-2"><h2 className="text-lg font-semibold text-slate-950">{formatWeek(week.weekStart)}</h2><span className={`rounded-full px-2.5 py-1 text-[11px] font-semibold ${weekClass(week.status)}`}>{weekLabel(week.status)}</span></div><p className="mt-1 text-xs text-slate-500">America/Sao_Paulo · {week.stories.length} conteúdos</p></div><div className="flex flex-wrap gap-2">{!closed && (week.status === 'approved' ? <><button type="button" disabled={busy} onClick={() => onDraft().catch(() => {})} className="rounded-xl border border-slate-200 px-3 py-2 text-xs font-semibold text-slate-700">Voltar para rascunho</button><button type="button" disabled={busy} onClick={() => onClose().catch(() => {})} className="inline-flex items-center gap-2 rounded-xl bg-slate-950 px-3 py-2 text-xs font-semibold text-white"><LockKeyhole size={14}/> Encerrar semana</button></> : <button type="button" disabled={busy} onClick={() => onApprove().catch(() => {})} className="inline-flex items-center gap-2 rounded-xl bg-emerald-600 px-3 py-2 text-xs font-semibold text-white disabled:opacity-50"><Check size={14}/> Aprovar semana</button>)}<button type="button" disabled={busy} onClick={onDelete} aria-label="Excluir semana" className="rounded-xl border border-rose-200 p-2 text-rose-600"><Trash2 size={15}/></button></div></div>; }
function StoryRow({ story, onEdit, onDelete, readOnly = false }) { return <article className="flex items-center gap-4 rounded-2xl border border-slate-200 bg-white p-4"><div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl bg-slate-100 text-slate-500"><span className="text-sm font-bold">{story.order}</span></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-slate-900">{story.productLabel}{story.priority ? ' · Prioritário' : ''}</p><p className="mt-1 text-xs text-slate-500">{formatDate(story.scheduledDate)} · {story.scheduledTime} · {story.categoryLabel || 'Sem categoria'}</p></div><span className={`hidden rounded-full px-2 py-1 text-[10px] font-semibold sm:block ${editorialClass(story.editorialStatus)}`}>{editorialLabel(story.editorialStatus)}</span>{!readOnly && <><button type="button" aria-label={`Editar ${story.productLabel}`} onClick={onEdit} className="p-2 text-slate-500"><Pencil size={15}/></button><button type="button" aria-label={`Excluir ${story.productLabel}`} onClick={onDelete} className="p-2 text-rose-500"><Trash2 size={15}/></button></>}</article>; }
function CalendarView({ week, onEdit, readOnly }) { const days = Array.from({ length: 7 }, (_, index) => addDays(week.weekStart, index)); const now = new Date(); return <div className="grid gap-3 md:grid-cols-2 2xl:grid-cols-7">{days.map((date) => <section key={date} className="min-h-48 rounded-2xl border border-slate-200 bg-white p-3"><p className="text-xs font-semibold uppercase tracking-wide text-slate-400">{formatDate(date)}</p><div className="mt-3 space-y-2">{week.stories.filter((story) => story.scheduledDate === date).map((story) => { const overdue = story.editorialStatus !== 'published' && new Date(`${story.scheduledDate}T${story.scheduledTime}:00-03:00`) < now; return <button key={story.id} type="button" disabled={readOnly} onClick={() => onEdit(story)} className="w-full overflow-hidden rounded-xl bg-slate-50 text-left disabled:cursor-default"><img src={marketingAssetUrl(week.id, story.id, 'source')} alt={`Fonte de ${story.productLabel}`} className="aspect-square w-full bg-slate-100 object-contain"/><span className="block p-3"><span className="flex items-center justify-between gap-2 text-[11px] font-semibold text-slate-500"><span>{story.scheduledTime}</span><span className={overdue ? 'text-rose-600' : ''}>{overdue ? 'Atrasado' : editorialLabel(story.editorialStatus)}</span></span><span className="mt-1 block text-xs font-semibold text-slate-900">{story.productLabel}</span><span className="mt-1 block text-[10px] text-slate-500">{story.categoryLabel || 'Sem categoria'}</span></span></button>; })}</div></section>)}</div>; }
function StoriesView({ week, layouts, busy, readOnly, onRender, onStatus, onOpenResult, onEdit }) { return week.stories.length ? <div className="grid gap-5 sm:grid-cols-2 2xl:grid-cols-3">{week.stories.map((story) => <article key={story.id} className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="aspect-[9/16] bg-slate-100">{story.renderStatus === 'ready' ? <img src={marketingAssetUrl(week.id, story.id, 'story')} alt={`Story de ${story.productLabel}`} className="h-full w-full object-contain"/> : <div className="flex h-full flex-col items-center justify-center px-6 text-center"><Sparkles size={24} className="text-slate-400"/><p className="mt-3 text-sm font-semibold text-slate-700">Story ainda não renderizado</p>{story.renderError?.message && <p className="mt-2 text-xs text-rose-600">{story.renderError.message}</p>}</div>}</div><div className="p-4"><div className="flex items-start justify-between gap-2"><div><p className="text-sm font-semibold text-slate-900">{story.productLabel}</p><p className="mt-1 text-xs text-slate-500">{story.categoryLabel || 'Sem categoria'} · {layouts.find((layout) => layout.id === story.storyTemplateId)?.label}</p></div><span className={`rounded-full px-2 py-1 text-[10px] font-semibold ${editorialClass(story.editorialStatus)}`}>{editorialLabel(story.editorialStatus)}</span></div><div className="mt-4 flex flex-wrap gap-2">{story.renderStatus === 'ready' && <a href={marketingAssetUrl(week.id, story.id, 'story')} download className="inline-flex items-center gap-1.5 rounded-lg border border-slate-200 px-3 py-2 text-xs font-semibold text-slate-700"><Download size={14}/> Download</a>}<button type="button" onClick={() => onOpenResult(story.sourceResultId)} className="inline-flex items-center gap-1.5 rounded-lg border border-slate-200 px-3 py-2 text-xs font-semibold text-slate-700"><ExternalLink size={14}/> Resultado</button>{!readOnly && <><button type="button" disabled={busy} onClick={() => onRender(story.id)} className="inline-flex items-center gap-1.5 rounded-lg bg-slate-950 px-3 py-2 text-xs font-semibold text-white disabled:opacity-50"><RefreshCw size={14}/> {story.renderStatus === 'ready' ? 'Renderizar novamente' : 'Renderizar'}</button>{story.renderStatus === 'ready' && <button type="button" disabled={busy} onClick={() => onStatus(story.id, story.editorialStatus === 'published' ? 'ready' : 'published')} className="rounded-lg border border-emerald-200 px-3 py-2 text-xs font-semibold text-emerald-700">{story.editorialStatus === 'published' ? 'Voltar para pronto' : 'Marcar publicado'}</button>}<button type="button" aria-label={`Editar ${story.productLabel}`} onClick={() => onEdit(story)} className="rounded-lg p-2 text-slate-500"><Pencil size={14}/></button></>}</div></div></article>)}</div> : <EmptyStories/>; }
function HistoryView({ weeks, onSelect }) { return <div className="space-y-3">{weeks.map((week) => { const totals = editorialTotals(week.stories); const categories = [...new Set(week.stories.map((story) => story.categoryLabel || 'Sem categoria'))]; return <button key={week.id} type="button" onClick={() => onSelect(week.id)} className="flex w-full flex-col gap-3 rounded-2xl border border-slate-200 bg-white p-5 text-left sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-semibold text-slate-900">{formatWeek(week.weekStart)}</p><p className="mt-1 text-xs text-slate-500">{week.stories.length} Stories · {totals.planned} planejados · {totals.ready} prontos · {totals.published} publicados</p><p className="mt-1 text-[11px] text-slate-400">Categorias: {categories.join(', ') || 'Nenhuma'} · aprovação: {formatTimestamp(week.approvedAt)} · atualizado em {formatTimestamp(week.updatedAt)}</p></div><span className={`rounded-full px-3 py-1 text-xs font-semibold ${weekClass(week.status)}`}>{weekLabel(week.status)}</span></button>; })}</div>; }
function Field({ label, children }) { return <label className="block"><span className="mb-1.5 block text-xs font-semibold text-slate-700">{label}</span>{children}</label>; }
function Loading() { return <div className="flex min-h-[420px] items-center justify-center rounded-2xl border border-slate-200 bg-white"><Loader2 className="animate-spin text-slate-500"/></div>; }
function ErrorState({ message, onRetry }) { return <div role="alert" className="rounded-2xl border border-rose-200 bg-rose-50 p-5 text-sm text-rose-800"><p className="font-semibold">O Marketing Studio não carregou.</p><p className="mt-1">{message}</p><button type="button" onClick={() => onRetry().catch(() => {})} className="mt-3 font-semibold underline">Tentar novamente</button></div>; }
function EmptyWeek({ onCreate }) { return <div className="flex min-h-[420px] flex-col items-center justify-center rounded-2xl border border-dashed border-slate-300 bg-white px-6 text-center"><CalendarDays size={30} className="text-slate-400"/><h2 className="mt-4 text-base font-semibold text-slate-900">Nenhuma semana planejada</h2><p className="mt-2 max-w-sm text-sm text-slate-500">Crie a primeira semana para organizar os resultados aprovados.</p><button type="button" onClick={onCreate} className="mt-5 rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white">Criar semana atual</button></div>; }
function EmptyStories() { return <div className="flex min-h-64 flex-col items-center justify-center rounded-2xl border border-dashed border-slate-300 bg-white p-6 text-center"><ImagePlus size={26} className="text-slate-400"/><p className="mt-3 text-sm font-semibold text-slate-800">Nenhum Story nesta semana</p></div>; }
function ConfirmDialog({ title, body, busy, onCancel, onConfirm }) { return <div className="fixed inset-0 z-[70] flex items-center justify-center bg-slate-950/65 p-4"><div role="alertdialog" aria-modal="true" className="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl"><AlertCircle className="text-rose-600"/><h2 className="mt-4 text-lg font-semibold text-slate-950">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-500">{body}</p><div className="mt-6 flex justify-end gap-3"><button type="button" disabled={busy} onClick={onCancel} className="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-semibold">Cancelar</button><button type="button" disabled={busy} onClick={onConfirm} className="rounded-xl bg-rose-600 px-4 py-2.5 text-sm font-semibold text-white">Excluir</button></div></div></div>; }

const inputClass = 'w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none transition focus:border-slate-500 disabled:bg-slate-100';
function addDays(value, amount) { const date = new Date(`${value}T12:00:00Z`); date.setUTCDate(date.getUTCDate() + amount); return date.toISOString().slice(0, 10); }
function currentMonday() { const parts = new Intl.DateTimeFormat('en-CA', { timeZone: 'America/Sao_Paulo', year: 'numeric', month: '2-digit', day: '2-digit' }).format(new Date()); const date = new Date(`${parts}T12:00:00Z`); const distance = (date.getUTCDay() + 6) % 7; date.setUTCDate(date.getUTCDate() - distance); return date.toISOString().slice(0, 10); }
function mondayForDate(value) { if (!value) return currentMonday(); const date = new Date(`${value}T12:00:00Z`); const distance = (date.getUTCDay() + 6) % 7; date.setUTCDate(date.getUTCDate() - distance); return date.toISOString().slice(0, 10); }
function formatDate(value) { return new Intl.DateTimeFormat('pt-BR', { day: '2-digit', month: 'short', timeZone: 'UTC' }).format(new Date(`${value}T12:00:00Z`)); }
function formatWeek(value) { return `${formatDate(value)} — ${formatDate(addDays(value, 6))}`; }
function formatTimestamp(value) { return value ? new Intl.DateTimeFormat('pt-BR', { dateStyle: 'short', timeStyle: 'short', timeZone: 'America/Sao_Paulo' }).format(new Date(value)) : 'Não informado'; }
function findNext(stories) { const now = new Date(); return stories.filter((story) => (story.editorialStatus || (story.renderStatus === 'ready' ? 'ready' : 'planned')) !== 'published').map((story) => ({ ...story, instant: new Date(`${story.scheduledDate}T${story.scheduledTime}:00-03:00`) })).filter((story) => story.instant >= now).sort((a, b) => a.instant - b.instant)[0] || null; }
function editorialLabel(status) { return status === 'published' ? 'Publicado' : status === 'ready' ? 'Pronto' : 'Planejado'; }
function editorialClass(status) { return status === 'published' ? 'bg-indigo-50 text-indigo-700' : status === 'ready' ? 'bg-emerald-50 text-emerald-700' : 'bg-amber-50 text-amber-700'; }
function editorialTotals(stories) { return stories.reduce((totals, story) => { const status = story.editorialStatus || (story.renderStatus === 'ready' ? 'ready' : 'planned'); totals[status] += 1; return totals; }, { planned: 0, ready: 0, published: 0 }); }
function weekLabel(status) { return status === 'closed' ? 'Encerrada' : status === 'approved' ? 'Aprovada' : 'Rascunho'; }
function weekClass(status) { return status === 'closed' ? 'bg-slate-200 text-slate-700' : status === 'approved' ? 'bg-emerald-50 text-emerald-700' : 'bg-amber-50 text-amber-700'; }
